server:
  port: 4044

runs-locally: ${RUNS_LOCALLY:true}

env: ${test_environment:local}
TEST_URL: http://localhost:8099

case:
  orchestration:
    service:
      base:
        uri: '#{environment["TEST_URL"].replaceFirst("https://", "http://")}'

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info

springdoc:
  packagesToScan: uk.gov.hmcts.reform.cosapi.controllers

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/fis/"
  application:
    name: Fis Cos API
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_OPTIONS:}
#    username: ${DB_USER_NAME}
#    password: ${DB_PASSWORD}
#    properties:
#      charSet: UTF-8
#    hikari:
#      minimumIdle: 2
#      maximumPoolSize: 10
#      idleTimeout: 10000
#      poolName: {to-be-defined}HikariCP
#      maxLifetime: 7200000
#      connectionTimeout: 30000
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            # silence the 'wall-of-text' - unnecessary exception throw about blob types
#            non_contextual_creation: true

azure:
  application-insights:
    instrumentation-key: ${AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

uk:
  gov:
    notify:
      api:
        key: ${UK_GOV_NOTIFY_API_KEY:dummy}
        baseUrl: https://api.notifications.service.gov.uk
      email:
        templateVars:
          signInAdoptionUrl: ${NOTIFY_TEMPLATE_SIGN_IN_ADOPTION_URL:https://adoption-web.aat.platform.hmcts.net/}
          adoptionCourtEmail: some.email@justice.gov.uk
        templates:
          english:
            TEST_EMAIL: ''
          welsh:
            TEST_EMAIL: ''

idam:
  s2s-auth:
    url: ${SERVICE_AUTH_PROVIDER_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
    secret: ${S2S_SECRET:XXXXXXXX}
    microservice: fis_cos_api
  api:
    url: https://idam-api.aat.platform.hmcts.net
  client:
    id: 'ds-ui'
    secret: ${OAUTH2_CLIENT_SECRET:AAAAAA}
    redirect_uri: ${IDAM_API_REDIRECT_URL:http://localhost:3000/oauth2/callback}
  systemupdate:
    username: ${IDAM_SYSTEM_UPDATE_USERNAME:dummysystemupdate@test.com}
    password: ${IDAM_SYSTEM_UPDATE_PASSWORD:dummy}

core_case_data:
  api:
    url: ${CASE_DATA_STORE_BASEURL:http://ccd-data-store-api-aat.service.core-compute-aat.internal}

case_document_am:
  url: ${CCD_CASE_DOCS_AM_API:http://ccd-case-document-am-api-aat.service.core-compute-aat.internal}

document_management:
  url: ${DOCUMENT_MANAGEMENT_URL:http://dm-store-aat.service.core-compute-aat.internal}
