apiVersion: v2
appVersion: "1.0"
description: A Helm chart for fis-cos-api App
name: fis-cos-api
home: https://github.com/hmcts/fis-cos-api
version: 0.0.7
maintainers:
  - name: HMCTS fis team
dependencies:
  - name: java
    version: 3.7.7
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: ccd
    version: 7.1.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    tags:
      - ccd-idam-pr
  - name: xui-webapp
    version: ~0.2.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: xui-webapp.enabled


