java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    CITIZEN_UPDATE_CASE_STATE_ENABLED: true
    SERVICE_AUTH_PROVIDER_URL: 'http://rpe-service-auth-provider-aat.service.core-compute-aat.internal'
    IDAM_WEB_URL: 'https://idam-web-public.aat.platform.hmcts.net/login'
    IDAM_API_URL: 'https://idam-api.aat.platform.hmcts.net'
    IDAM_API_BASEURL: 'https://idam-api.aat.platform.hmcts.net'
    CASE_DATA_STORE_BASEURL: 'https://ccd-data-store-api-aat.service.core-compute-aat.internal'
    CCD_CASE_DOCS_AM_API: "http://ccd-case-document-am-api-aat.service.core-compute-aat.internal"


  keyVaults:
    fis-kv:
      secrets:
        - name: uk-gov-notify-api-key
          alias: UK_GOV_NOTIFY_API_KEY
        - name: s2s-secret-fis-cos-api
          alias: S2S_SECRET
        - name: idam-system-user-name
          alias: IDAM_SYSTEM_UPDATE_USERNAME
        - name: idam-system-user-password
          alias: IDAM_SYSTEM_UPDATE_PASSWORD
        - name: idam-ui-secret
          alias: OAUTH2_CLIENT_SECRET
