java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    CASE_DATA_STORE_BASEURL: http://fis-cos-api-pr-${CHANGE_ID}-ccd-data-store-api
    CITIZEN_UPDATE_CASE_STATE_ENABLED: true
    APP_INSIGHTS_KEY: 40c4ab72-faeb-4a79-b7ef-554038d0542f

  keyVaults:
    fis-kv:
      secrets:
        - name: uk-gov-notify-api-key
          alias: UK_GOV_NOTIFY_API_KEY
        - name: s2s-secret-fis-cos-api
          alias: S2S_SECRET
        - name: idam-system-user-name
          alias: IDAM_SYSTEM_UPDATE_USERNAME
        - name: idam-system-user-password
          alias: IDAM_SYSTEM_UPDATE_PASSWORD
        - name: idam-ui-secret
          alias: OAUTH2_CLIENT_SECRET